version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data_container:
